export enum AuditAction {
  READ = 'READ',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  EXPORT = 'EXPORT',
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FAILED_ACCESS = 'FAILED_ACCESS',
}
